config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users
    root to: 'products#index'
  resources :products do
    resources :reviews
  end
end


#
# Rails.application.routes.draw do
#   get 'pages/home'
#   devise_for :users
#     root to: 'products#index'
#   resources :products do
#     resources :reviews
#   end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)
  # scope :search, -> (product_parameter) { where("name like ?", "%#{product_parameter}%")}
  scope :buy_usa, -> { where(country_of_origin: "USA") }
  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, count(reviews.id) as number_of_reviews")
    .joins(:reviews)
    .group("products.id")
    .order("number_of_reviews DESC")
    .limit(1)
    )}

    private
    def titleize_product
      self.name = self.name.titleize
    end

  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates_length_of :content_body, maximum: 250
  validates_length_of :content_body, minimum: 50
  validates_length_of :rating, maximum: 5
  validates_length_of :rating, minimum: 1
  validates :author, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize
    if current_user.admin != true
      flash[:alert] = "Mario didn't grant you permission to use this functionality."
      redirect_to '/'
    end
  end

  def authorize_admin
    if current_user.admin != true
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to request.referrer
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:admin, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:admin, :email, :password, :current_password)}
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize, only: [:new, :edit, :destroy]
# before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @products = Product.all
    @usa_products = Product.buy_usa
    @three_most_recent = Product.three_most_recent
    @most_reviews = Product.most_reviews
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  # def ==(product_to_compare)
  #   if product_to_compare != nil
  #     self.name() == product_to_compare.title()
  #   else
  #     false
  #   end
  # end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authorize, only: [:edit, :destroy]
# before_action :authorize_admin, only: [:new, :create, :show]


  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end


  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>ERRORS!!! Please fix them:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cost %>
  <%= f.number_field :cost %>

  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>


  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario's Discount Specialty Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Marios Discount Specialty Foods</h1>

<% if user_signed_in? %>

<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %> <BR>

  <% else %>
  <%= link_to "Home", '/' %> | <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Sign in", new_user_session_path %>
  <% end %>

  <hr>

app/views/products/edit.html.erb
<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<div class="new-header">
  <h1 class="new-text">Edit Product</h1>
</div>
<hr class="hr-thick">
<hr class="hr-thin">

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<% if user_signed_in? %>

<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

<div class="header-top">
  <h1 class="header1">Mario's</h1>
  <h2 class="header2">Discount Specialty Foods</h2>
  <%= image_tag "mario.png" %>
</div>

<hr class="hr-thick">
<hr class="hr-thin">
<div class="container id="about">
  <div class="row">
    <div class="col-lg-12">
      <h5>Mario's Discount Specialty Foods specializes in specialty foods that are discounted. Mario provides tastebud-tickling specialty ingredients at discoutned rates which right wrongs and disolves trauma. Please support Mario's Discount Specialty Foods by purchasing Mario's discounted specialty products that are guarenteed to be edible.</h5>
    </div>
  </div>
</div>
<hr class="hr-thin">
<hr class="hr-thick">
<div class="header-middle">
  <h2 id="middle-text">Take a gander at Mario's Edible Products!</h2>
</div>

<% if current_user.admin  == true%>
<h4 id="create-new_product"><%= link_to "Create new product", new_product_path %></h4>
<% end %>

<div class="container">
  <div class="row">

    <div class="col-lg-3">
      <h3>All Products Available</h3>

      <% if @products.any? %>
      <ul>
        <% @products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
      <% else %>
      <p>There are no products yet.</p>
      <% end %>
    </div>

    <div class="col-lg-3">
      <h3>Products made in the USA</h3>
      <% if @usa_products.any? %>
      <ul>
        <% @usa_products.each do |product| %>
        <li><%= link_to product.name, product_path(product)%></li>
        <% end %>
      </ul>
      <% else %>
      <p>There are no products that are made in the USA in stock.</p>
      <% end %>
    </div>

    <div class="col-lg-3">
      <h3>The Three Most Recently Added Products</h3>
      <% if @three_most_recent.any? %>
      <ul>
        <% @three_most_recent.each do |product| %>
        <li><%= link_to product.name, product_path(product)%></li>
        <% end %>
      </ul>
      <% else %>
      <p>Looks like we don't have much in stock.</p>
      <% end %>
    </div>
    <div class="col-lg-3">
      <h3>Mario's Most Reviewed Product</h3>
      <% if @most_reviews.any? %>
      <ul>
        <% @most_reviews.each do |product| %>
        <li><%= link_to product.name, product_path(product)%></li>
        <% end %>
      </ul>
      <% else %>
      <p>Looks like we don't have much in the way of reviews.</p>
      <% end %>

    </div>
  </div>
</div>
<hr class="hr-thin">
<hr class="hr-thick">

<div class="bottom">

  <%= image_tag "pasta.png" %>

</div>



<% else %>
<%= link_to "Home", '/' %> | <%= link_to "Sign up", new_user_registration_path %> |
<%= link_to "Sign in", new_user_session_path %>
<hr>

<div class="header-top">
  <h1 class="header1">Mario's</h1>
  <h2 class="header2">Discount Specialty Foods</h2>
  <%= image_tag "mario.png" %>
</div>

<hr class="hr-thin">
<div class="container id="about">
  <div class="row">
    <div class="col-lg-12">
  <h1>Please sign up or sign in to peruse Mario's edible food stuffs.</h1>
    </div>
  </div>
</div>
<hr class="hr-thin">
<div class="header-middle">
  <h2 id="middle-text">Yum, Yum. Delicious Food.</h2>
</div>
<hr class="hr-thin">
<br>


<br>
<hr class="hr-thin">
<% end %>

app/views/products/new.html.erb
<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% if @product.errors.any? %>
<h3 class="error">Please fix these errors:</h3>
<ul>
  <% @product.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<div class="new-header">
  <h1 class="new-text">Let's make a new product.</h1>
</div>
<hr class="hr-thick">
<hr class="hr-thin">
<%= render "layouts/product_form" %>
<hr>
<p><%= link_to "Return to products", products_path %></p>

app/views/products/show.html.erb
<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<div class="new-header">
  <h1 class="new-text">Let's Investigate a product and the product reviews</h1>
</div>
<hr class="hr-thick">
<hr class="hr-thin">

<h1><%= @product.name %></h1>
<h3><%= @product.cost %> $ USD + shipping and handling</h3>
<h3>Ships from: <%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
<h4>Here are the reviews for this product:</h4>
<hr>

<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= link_to review.author, product_review_path(@product, review) %>
  </li>
</ul>
<% end %>
<% else %>
<p>No reviews are listed for this product.</p>
<% end %>
<hr>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p> | </p>

<% if current_user.admin  == true%>
<p><%= link_to "Edit Product", edit_product_path(@product) %></p>
<p> | </p>
<p><%= link_to "Delete product", product_path(@product),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>
  <p> | </p>

  <% end %>


  <p><%= link_to "Return to products", products_path %></p>

  <br>
  <br>

app/views/reviews/edit.html.erb
<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<div class="new-header">
  <h1 class="new-text">Edit Review</h1>
</div>
<hr class="hr-thick">
<hr class="hr-thin">


<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :content_body %>
  <%= f.text_area :content_body %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <h2 class="error">ERROR, ERROR, ERROR</h2>
  <h3 class="error">You have an error.</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>





<h1>Add a new review:</h1>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>

<%= f.label :content_body %>
<%= f.text_area :content_body %>

<%= f.label :rating %>
<%= f.number_field :rating %>

<p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<%= link_to "Home", '/' %> |
Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<div class="new-header">
  <h1 class="new-text">Product review</h1>
</div>
<hr class="hr-thick">
<hr class="hr-thin">


<h1>Review written by: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h3><%= @review.author %></h3>
<h3><%= @review.content_body %></h3>
<h3><%= @review.rating %> out of 5 Stars</h3>
<hr>
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>

<p> | </p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p> | </p>
<p><%= link_to "Return to product", product_path(@product) %></p>